# "DELETE" means this column will be removed from the output file
# "" means the name will not be changed
# "CertainMetricNames" means the name will be changed to "CertainMetricNames"


COL_NAMES = {
    ('parse_cutadapt_trim_stats', 'status'): 'DELETE',
    ('parse_cutadapt_trim_stats', 'in_reads'): 'InputReadPairs',
    ('parse_cutadapt_trim_stats', 'in_bp'): 'InputReadPairsBP',
    ('parse_cutadapt_trim_stats', 'too_short'): 'DELETE',
    ('parse_cutadapt_trim_stats', 'too_long'): 'DELETE',
    ('parse_cutadapt_trim_stats', 'too_many_n'): 'DELETE',
    ('parse_cutadapt_trim_stats', 'out_reads'): 'TrimmedReadPairs',
    ('parse_cutadapt_trim_stats', 'w/adapters'): 'R1WithAdapters',
    ('parse_cutadapt_trim_stats', 'qualtrim_bp'): 'R1QualTrimBP',
    ('parse_cutadapt_trim_stats', 'out_bp'): 'R1TrimmedReadsBP',
    ('parse_cutadapt_trim_stats', 'w/adapters2'): 'R2WithAdapters',
    ('parse_cutadapt_trim_stats', 'qualtrim2_bp'): 'R2QualTrimBP',
    ('parse_cutadapt_trim_stats', 'out2_bp'): 'R2TrimmedReadsBP',
    ('parse_hisat_summary', 'ReadPairsMappedInPE'): 'DELETE',
    ('parse_hisat_summary', 'PEUnmappableReadPairs'): 'DELETE',
    ('parse_hisat_summary', 'PEUniqueMappedReadPairs'): 'DELETE',
    ('parse_hisat_summary', 'PEMultiMappedReadPairs'): 'DELETE',
    ('parse_hisat_summary', 'PEDiscordantlyUniqueMappedReadPairs'): 'DELETE',
    ('parse_hisat_summary', 'ReadsMappedInSE'): 'DELETE',
    ('parse_hisat_summary', 'SEUnmappableReads'): 'DELETE',
    ('parse_hisat_summary', 'SEUniqueMappedReads'): 'DELETE',
    ('parse_hisat_summary', 'SEMultiMappedReads'): 'DELETE',
    ('parse_hisat_summary', 'UniqueMappedReads'): 'UniqueMappedReads',
    ('parse_hisat_summary', 'MultiMappedReads'): 'MultiMappedReads',
    ('parse_hisat_summary', 'UniqueMappingRate'): 'UniqueMappingRate',
    ('parse_hisat_summary', 'MultiMappingRate'): 'MultiMappingRate',
    ('parse_hisat_summary', 'OverallMappingRate'): 'OverallMappingRate',
    ('parse_picard_dedup_stat', 'LIBRARY'): 'DELETE',
    ('parse_picard_dedup_stat', 'UNPAIRED_READS_EXAMINED'): 'DELETE',
    ('parse_picard_dedup_stat', 'READ_PAIRS_EXAMINED'): 'DELETE',
    ('parse_picard_dedup_stat', 'SECONDARY_OR_SUPPLEMENTARY_RDS'): 'DELETE',
    ('parse_picard_dedup_stat', 'UNMAPPED_READS'): 'DELETE',
    ('parse_picard_dedup_stat', 'UNPAIRED_READ_DUPLICATES'): 'DELETE',
    ('parse_picard_dedup_stat', 'READ_PAIR_DUPLICATES'): 'DELETE',
    ('parse_picard_dedup_stat', 'READ_PAIR_OPTICAL_DUPLICATES'): 'DELETE',
    ('parse_picard_dedup_stat', 'PERCENT_DUPLICATION'): 'DELETE',
    ('parse_picard_dedup_stat', 'ESTIMATED_LIBRARY_SIZE'): 'DELETE',
    ('parse_picard_dedup_stat', 'FinalReads'): '',
    ('parse_picard_dedup_stat', 'DuplicatedReads'): '',
    ('parse_picard_dedup_stat', 'PCRDuplicationRate'): '',
}